opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Build and upload Rosetta to TestFlight"

  lane :beta do
    bundle_id = "com.academy.hendraaaa.Rosetta"

    team_id = ENV.fetch("APPLE_TEAM_ID")
    profile_name = ENV.fetch("PROFILE_NAME")
    profile_uuid = ENV.fetch("PROFILE_UUID")

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_KEY_CONTENT_BASE64"),
      is_key_content_base64: true,
      duration: 1200,
      in_house: false
    )

    increment_build_number(
      xcodeproj: "GameClassification.xcodeproj",
      build_number: ENV.fetch("GITHUB_RUN_NUMBER")
    )

    build_app(
      project: "GameClassification.xcodeproj",
      scheme: "GameClassification",
      configuration: "Release",
      clean: true,

      output_directory: "build",
      output_name: "Rosetta.ipa",

      export_method: "app-store",
      skip_profile_detection: true,
      codesigning_identity: "Apple Distribution",

      xcargs: [
        "DEVELOPMENT_TEAM=#{team_id}",
        "PRODUCT_BUNDLE_IDENTIFIER=#{bundle_id}",
        "CODE_SIGN_STYLE=Manual",
        'CODE_SIGN_IDENTITY="Apple Distribution"',
        "PROVISIONING_PROFILE_SPECIFIER=#{profile_uuid}"
      ].join(" "),

      export_options: {
        signingStyle: "manual",
        teamID: team_id,
        signingCertificate: "Apple Distribution",
        provisioningProfiles: {
          bundle_id => profile_name
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: bundle_id,
      apple_id: ENV.fetch("APP_STORE_APP_ID"),
      ipa: "build/Rosetta.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
